/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.autonoma.gui;

import co.edu.autonoma.actores.Operario;
import javax.swing.JOptionPane;

/**
 *
 * @author Manuela Cardona
 */
public class Login extends javax.swing.JFrame {

    Operario operario;
    
    /**
     * Creates new form Login
     */
    public Login(Operario operario) {
        initComponents();
        this.operario = operario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JButton();
        txtfIpServidor = new javax.swing.JTextField();
        TxtFNombreOperario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLANTA NUCLEAR SPRINGFIELD");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 60, 410, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ip Servidor:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 220, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(220, 170, 70, 17);

        BtnEntrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnEntrar.setText("Entrar");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnEntrar);
        BtnEntrar.setBounds(340, 270, 90, 25);
        jPanel1.add(txtfIpServidor);
        txtfIpServidor.setBounds(310, 220, 180, 30);
        jPanel1.add(TxtFNombreOperario);
        TxtFNombreOperario.setBounds(310, 170, 180, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PlantaNuclear.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        
        String nombreOperario = TxtFNombreOperario.getText();
        
        this.operario.setNombre(nombreOperario);
        
        this.operario.setIpServidor(txtfIpServidor.getText());
        
        if(this.operario.getNombre().trim().isEmpty() | this.operario.getIpServidor().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Completar los datos del login", "Login", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        boolean conexion = this.operario.conectarAServidor();
        
        if(conexion){
            PanelControlPlantaN principal = new PanelControlPlantaN(operario);
            
            principal.setLocationRelativeTo(null);
            principal.setVisible(true);
            principal.iniciarEntrada();
            
            this.dispose();
            
            
        }else{
            JOptionPane.showMessageDialog(this, "Error conectando con el servidor solicitado", "Conexión", JOptionPane.INFORMATION_MESSAGE);
        }    
    }//GEN-LAST:event_BtnEntrarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JTextField TxtFNombreOperario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtfIpServidor;
    // End of variables declaration//GEN-END:variables
}
